### ISSUE TITLE
Update Profile Readme temen temen Mentoring 1

### ISSUE THREAD

**Issue by sanggusti** [sanggusti/mentoring-skilvul-sic#19]
details yang diperlukan:
- Tim
- Sekolah dimana
- Hobi

**Comment by sanggusti** [comment]
@GladysAmel

**Comment by sanggusti** [comment]
Tolong tambahkan pull request yang sesuai dengan problem ini @Nadhifah-Hanan

**Comment by Nadhifah-Hanan** [comment]
sudah aku tambahkan sesuai dengan pull request diatas ya kak #20
